export interface EmojiMap {
  [key: string]: {
    cover: string;
    data: {
      [key: string]: string;
    };
  };
}

const emojiMap: EmojiMap = {
  小黄脸: {
    cover: "http://static.init.center/common/emoji/小黄脸/微笑.jpg",
    data: {
      微笑: "http://static.init.center/common/emoji/小黄脸/微笑.jpg",
      龇牙: "http://static.init.center/common/emoji/小黄脸/龇牙.jpg",
      OK: "http://static.init.center/common/emoji/小黄脸/OK.jpg",
      星星眼: "http://static.init.center/common/emoji/小黄脸/星星眼.jpg",
      哦呼: "http://static.init.center/common/emoji/小黄脸/哦呼.jpg",
      歪嘴: "http://static.init.center/common/emoji/小黄脸/歪嘴.jpg",
      嫌弃: "http://static.init.center/common/emoji/小黄脸/嫌弃.jpg",
      喜欢: "http://static.init.center/common/emoji/小黄脸/喜欢.jpg",
      酸了: "http://static.init.center/common/emoji/小黄脸/酸了.jpg",
      大哭: "http://static.init.center/common/emoji/小黄脸/大哭.jpg",
      害羞: "http://static.init.center/common/emoji/小黄脸/害羞.jpg",
      疑惑: "http://static.init.center/common/emoji/小黄脸/疑惑.jpg",
      辣眼睛: "http://static.init.center/common/emoji/小黄脸/辣眼睛.jpg",
      调皮: "http://static.init.center/common/emoji/小黄脸/调皮.jpg",
      喜极而泣: "http://static.init.center/common/emoji/小黄脸/喜极而泣.jpg",
      奸笑: "http://static.init.center/common/emoji/小黄脸/奸笑.jpg",
      笑: "http://static.init.center/common/emoji/小黄脸/笑.jpg",
      偷笑: "http://static.init.center/common/emoji/小黄脸/偷笑.jpg",
      大笑: "http://static.init.center/common/emoji/小黄脸/大笑.jpg",
      阴险: "http://static.init.center/common/emoji/小黄脸/阴险.jpg",
      捂脸: "http://static.init.center/common/emoji/小黄脸/捂脸.jpg",
      囧: "http://static.init.center/common/emoji/小黄脸/囧.jpg",
      呆: "http://static.init.center/common/emoji/小黄脸/呆.jpg",
      抠鼻: "http://static.init.center/common/emoji/小黄脸/抠鼻.jpg",
      惊喜: "http://static.init.center/common/emoji/小黄脸/惊喜.jpg",
      惊讶: "http://static.init.center/common/emoji/小黄脸/惊讶.jpg",
      笑哭: "http://static.init.center/common/emoji/小黄脸/笑哭.jpg",
      妙啊: "http://static.init.center/common/emoji/小黄脸/妙啊.jpg",
      doge: "http://static.init.center/common/emoji/小黄脸/doge.jpg",
      滑稽: "http://static.init.center/common/emoji/小黄脸/滑稽.jpg",
      吃瓜: "http://static.init.center/common/emoji/小黄脸/吃瓜.jpg",
      打call: "http://static.init.center/common/emoji/小黄脸/打call.jpg",
      点赞: "http://static.init.center/common/emoji/小黄脸/点赞.jpg",
      鼓掌: "http://static.init.center/common/emoji/小黄脸/鼓掌.jpg",
      尴尬: "http://static.init.center/common/emoji/小黄脸/尴尬.jpg",
      冷: "http://static.init.center/common/emoji/小黄脸/冷.jpg",
      灵魂出窍: "http://static.init.center/common/emoji/小黄脸/灵魂出窍.jpg",
      委屈: "http://static.init.center/common/emoji/小黄脸/委屈.jpg",
      傲娇: "http://static.init.center/common/emoji/小黄脸/傲娇.jpg",
      疼: "http://static.init.center/common/emoji/小黄脸/疼.jpg",
      吓: "http://static.init.center/common/emoji/小黄脸/吓.jpg",
      生病: "http://static.init.center/common/emoji/小黄脸/生病.jpg",
      吐: "http://static.init.center/common/emoji/小黄脸/吐.jpg",
      嘘声: "http://static.init.center/common/emoji/小黄脸/嘘声.jpg",
      捂眼: "http://static.init.center/common/emoji/小黄脸/捂眼.jpg",
      思考: "http://static.init.center/common/emoji/小黄脸/思考.jpg",
      再见: "http://static.init.center/common/emoji/小黄脸/再见.jpg",
      翻白眼: "http://static.init.center/common/emoji/小黄脸/翻白眼.jpg",
      哈欠: "http://static.init.center/common/emoji/小黄脸/哈欠.jpg",
      奋斗: "http://static.init.center/common/emoji/小黄脸/奋斗.jpg",
      墨镜: "http://static.init.center/common/emoji/小黄脸/墨镜.jpg",
      难过: "http://static.init.center/common/emoji/小黄脸/难过.jpg",
      撇嘴: "http://static.init.center/common/emoji/小黄脸/撇嘴.jpg",
      抓狂: "http://static.init.center/common/emoji/小黄脸/抓狂.jpg",
      生气: "http://static.init.center/common/emoji/小黄脸/生气.jpg",
      口罩: "http://static.init.center/common/emoji/小黄脸/口罩.jpg",
      月饼: "http://static.init.center/common/emoji/小黄脸/月饼.jpg",
      视频卫星: "http://static.init.center/common/emoji/小黄脸/视频卫星.jpg",
      鸡腿: "http://static.init.center/common/emoji/小黄脸/鸡腿.jpg",
      干杯: "http://static.init.center/common/emoji/小黄脸/干杯.jpg",
      爱心: "http://static.init.center/common/emoji/小黄脸/爱心.jpg",
      锦鲤: "http://static.init.center/common/emoji/小黄脸/锦鲤.jpg",
      胜利: "http://static.init.center/common/emoji/小黄脸/胜利.jpg",
      加油: "http://static.init.center/common/emoji/小黄脸/加油.jpg",
      保佑: "http://static.init.center/common/emoji/小黄脸/保佑.jpg",
      抱拳: "http://static.init.center/common/emoji/小黄脸/抱拳.jpg",
      响指: "http://static.init.center/common/emoji/小黄脸/响指.jpg",
      支持: "http://static.init.center/common/emoji/小黄脸/支持.jpg",
      拥抱: "http://static.init.center/common/emoji/小黄脸/拥抱.jpg",
      怪我咯: "http://static.init.center/common/emoji/小黄脸/怪我咯.jpg",
      跪了: "http://static.init.center/common/emoji/小黄脸/跪了.jpg",
      黑洞: "http://static.init.center/common/emoji/小黄脸/黑洞.jpg",
      福到了: "http://static.init.center/common/emoji/小黄脸/福到了.jpg",
    },
  },
  阿鲁: {
    cover: "http://static.init.center/common/emoji/阿鲁/长草.jpg",
    data: {
      吐: "http://static.init.center/common/emoji/阿鲁/吐.jpg",
      狂汗: "http://static.init.center/common/emoji/阿鲁/狂汗.jpg",
      不说话: "http://static.init.center/common/emoji/阿鲁/不说话.jpg",
      汗: "http://static.init.center/common/emoji/阿鲁/汗.jpg",
      献花: "http://static.init.center/common/emoji/阿鲁/献花.jpg",
      不高兴: "http://static.init.center/common/emoji/阿鲁/不高兴.jpg",
      中刀: "http://static.init.center/common/emoji/阿鲁/中刀.jpg",
      皱眉: "http://static.init.center/common/emoji/阿鲁/皱眉.jpg",
      小眼睛: "http://static.init.center/common/emoji/阿鲁/小眼睛.jpg",
      中指: "http://static.init.center/common/emoji/阿鲁/中指.jpg",
      尴尬: "http://static.init.center/common/emoji/阿鲁/尴尬.jpg",
      瞅你: "http://static.init.center/common/emoji/阿鲁/瞅你.jpg",
      想一想: "http://static.init.center/common/emoji/阿鲁/想一想.jpg",
      中枪: "http://static.init.center/common/emoji/阿鲁/中枪.jpg",
      得意: "http://static.init.center/common/emoji/阿鲁/得意.jpg",
      肿包: "http://static.init.center/common/emoji/阿鲁/肿包.jpg",
      扇耳光: "http://static.init.center/common/emoji/阿鲁/扇耳光.jpg",
      亲亲: "http://static.init.center/common/emoji/阿鲁/亲亲.jpg",
      惊喜: "http://static.init.center/common/emoji/阿鲁/惊喜.jpg",
      脸红: "http://static.init.center/common/emoji/阿鲁/脸红.jpg",
      无所谓: "http://static.init.center/common/emoji/阿鲁/无所谓.jpg",
      便便: "http://static.init.center/common/emoji/阿鲁/便便.jpg",
      愤怒: "http://static.init.center/common/emoji/阿鲁/愤怒.jpg",
      蜡烛: "http://static.init.center/common/emoji/阿鲁/蜡烛.jpg",
      内伤: "http://static.init.center/common/emoji/阿鲁/内伤.jpg",
      投降: "http://static.init.center/common/emoji/阿鲁/投降.jpg",
      观察: "http://static.init.center/common/emoji/阿鲁/观察.jpg",
      看不见: "http://static.init.center/common/emoji/阿鲁/看不见.jpg",
      抠鼻: "http://static.init.center/common/emoji/阿鲁/抠鼻.jpg",
      邪恶: "http://static.init.center/common/emoji/阿鲁/邪恶.jpg",
      看热闹: "http://static.init.center/common/emoji/阿鲁/看热闹.jpg",
      口水: "http://static.init.center/common/emoji/阿鲁/口水.jpg",
      抽烟: "http://static.init.center/common/emoji/阿鲁/抽烟.jpg",
      锁眉: "http://static.init.center/common/emoji/阿鲁/锁眉.jpg",
      装大款: "http://static.init.center/common/emoji/阿鲁/装大款.jpg",
      吐舌: "http://static.init.center/common/emoji/阿鲁/吐舌.jpg",
      无奈: "http://static.init.center/common/emoji/阿鲁/无奈.jpg",
      长草: "http://static.init.center/common/emoji/阿鲁/长草.jpg",
      赞一个: "http://static.init.center/common/emoji/阿鲁/赞一个.jpg",
      无语: "http://static.init.center/common/emoji/阿鲁/无语.jpg",
      阴暗: "http://static.init.center/common/emoji/阿鲁/阴暗.jpg",
      不出所料: "http://static.init.center/common/emoji/阿鲁/不出所料.jpg",
      咽气: "http://static.init.center/common/emoji/阿鲁/咽气.jpg",
      期待: "http://static.init.center/common/emoji/阿鲁/期待.jpg",
      高兴: "http://static.init.center/common/emoji/阿鲁/高兴.jpg",
      吐血倒地: "http://static.init.center/common/emoji/阿鲁/吐血倒地.jpg",
      哭泣: "http://static.init.center/common/emoji/阿鲁/哭泣.jpg",
      欢呼: "http://static.init.center/common/emoji/阿鲁/欢呼.jpg",
      黑线: "http://static.init.center/common/emoji/阿鲁/黑线.jpg",
      喷水: "http://static.init.center/common/emoji/阿鲁/喷水.jpg",
      深思: "http://static.init.center/common/emoji/阿鲁/深思.jpg",
      鼓掌: "http://static.init.center/common/emoji/阿鲁/鼓掌.jpg",
      暗地观察: "http://static.init.center/common/emoji/阿鲁/暗地观察.jpg",
    },
  },
};

export default emojiMap;
